// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCXfrkquYAtgrxNxi0MTz-7M_pN4fbaoB4',
    appId: '1:349024474460:web:fa8cfa8a7c6e757cd6dd99',
    messagingSenderId: '349024474460',
    projectId: 'smartsfa-f20a0',
    authDomain: 'smartsfa-f20a0.firebaseapp.com',
    storageBucket: 'smartsfa-f20a0.firebasestorage.app',
    measurementId: 'G-574C0NQRPG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAxg5dROfjXkQqp4Bn8342Gi3XPbmzjHg8',
    appId: '1:349024474460:android:56c2664e9d6eed48d6dd99',
    messagingSenderId: '349024474460',
    projectId: 'smartsfa-f20a0',
    storageBucket: 'smartsfa-f20a0.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDDxQXrwfOrJXT9JneFE3apaokH3SYx1jE',
    appId: '1:349024474460:ios:471f1b6d61c63ba9d6dd99',
    messagingSenderId: '349024474460',
    projectId: 'smartsfa-f20a0',
    storageBucket: 'smartsfa-f20a0.firebasestorage.app',
    iosBundleId: 'com.example.smartsfa',
  );
}
