// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDFXV_T5_WfN2xrl-qi814i_AwReyGjXKs',
    appId: '1:209774810668:web:791f214b9561d723d8e389',
    messagingSenderId: '209774810668',
    projectId: 'smart-sfa',
    authDomain: 'smart-sfa.firebaseapp.com',
    storageBucket: 'smart-sfa.firebasestorage.app',
    measurementId: 'G-C1FE0R0DBK',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAJNxHMIgAi0uRuTN_epmGc7ZKxBvASP0A',
    appId: '1:209774810668:android:c65d463954b4fb50d8e389',
    messagingSenderId: '209774810668',
    projectId: 'smart-sfa',
    storageBucket: 'smart-sfa.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCBSuz3gwzxTSC-OYUsI07ei_a-78ZBwXU',
    appId: '1:209774810668:ios:33b9601d3abb13d6d8e389',
    messagingSenderId: '209774810668',
    projectId: 'smart-sfa',
    storageBucket: 'smart-sfa.firebasestorage.app',
    iosClientId: '209774810668-cjifscpihdipd1i0ta9ja42mlki5omf4.apps.googleusercontent.com',
    iosBundleId: 'com.example.smartsfa',
  );
}
